import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'


import { getRandomPrompt } from '../utils';
import { FormField, Loader } from '../components';


//NAVIGATE BACK TO HOMEPAGE ONCE POST IS CREATED
const CreatePost = () => {
  const navigate = useNavigate();

  const [form, setForm] = useState({
    name: '',
    prompt: '',
    photo: '',
  });
  

  const [ generatingImg, setGeneratingImg] = useState(false);
  const [ loading, setLoading] = useState(false);

  const handleSubmit = () => {

  }
  const handleChange = (e) => setForm({ ...form, [e.target.name]: e.target.value });

  const handleSurpriseMe = () => {
    const randomPrompt = getRandomPrompt(form.prompt);
    setForm({ ...form, prompt: randomPrompt });
  };

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">Generate</h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w [500px]">Create imaginative and visually stunning images generated by IntelliGen and share them with the community!</p>
      </div>

     <form className="mt-16 max-w-3xl" onSubmit={handleSubmit}>
      <div className="flex flex-col gap-5">
        <FormField
          LabelName="Your name"
          type="text"
          name="name"
          placeholder="John Doe"
          value={form.name}
          handleChange={ handleChange }
          />
        <FormField
          LabelName="Prompt"
          type="text"
          name="prompt"
          placeholder="John Doe'an oil pastel drawing of an annoyed cat in a spaceship"
          value={form.prompt}
          handleChange={ handleChange }
          isSurpriseMe
          handleSurpriseMe={ handleSurpriseMe }
          />
        
      </div>

     </form>
    </section>
  )
}

export default CreatePost;